### ISSUE TITLE
Suggestion: Customizable output message

### ISSUE THREAD

**Issue by juan3036** [unicesi/amelia#3]
Through the use of the library. Sometimes I find relevant to show (print) messages that indicates the state of whatever amelia is deploying or running at some determinate time. This could be useful for example in reports to show output paths or error messages. 

Thanks

**Comment by jachinte** [comment]
Hi @juan3036,
Thanks for your suggestions! they are always welcomed :+1: 
I understand you want to be able to customize error/success messages, is that correct? Now, these customized messages are shown while commands are being executed? This may not be possible, at least at the moment, because the execution is delegated to a terminal. However, these messages can be actually shown at the end. In that case the default message would be replaced by the custom one.

**Comment by juan3036** [comment]
Hi @jachinte 
Yes, modifying the default message when a component or execution object is released could be helpful in some specific cases where a deployment is being executed.
Thanks,

**Comment by jachinte** [comment]
There you have it! To use it just call `withSuccessMessage` while building the execution descriptor. If no success message is given, the default is passed to the command: `<component> has been executed`
